export default {
  searchBuckets: 'Search Buckets',
  searchObjects: 'Search Objects',
  name: 'Name',
  size: 'Size',
  File: 'File',
  sign: 'Sign',
  fileType: 'File Type',
  storageType: 'Storage Type',
  lastModified: 'Last Modified',
  options: 'Options',
  download: 'Download',
  currentPath: 'CurrentPath',
  dialog: {
    cancel: 'Cancel',
    create: 'Create',
  },
  del: {
    delTitle: 'Delete',
    delMessage: 'Are you sure delete',
    delSuccess: 'Delete Success',
    delFail: 'Delete Fail',
    confirm: 'Delete',
    cancel: 'Cancel',
  },
  label: 'Label',
  addLabel: 'Add Label',
  upload: {
    uploadSuccess: 'Upload success',
    uploadFail: 'Upload fail',
    uploadButton: 'Upload',
    uploadFile: 'Upload file',
    uploadFolder: 'Upload folder',
  },
  new: { // 新建
    newButton: 'New',
    newFolder: 'New Folder',
    newFolderPlaceholder: 'Enter the folder name',

  },
  share: {
    title: 'File Share',
    utils: 'Default (7 Days)',
    selectDate: 'Select a date',
    copy: 'Copy',
    copySuccess: 'Copy Success',
    notSupport: 'Browser does not support',
  },
  down: {
    downBigTips: 'Download process started, it may take a few moments to complete',
  },
}
